// const animationList = {
//   walk: { path: '/WalkingPaul.glb', index: 0 },
//   run: { path: '/RunningPaul.glb', index: 0 },
//   idle: {path: '/IdlePaul.glb', index:0},
//   leftTurn: {path: '/LeftTurnPaul.glb', index:0},
//   rightTurn: {path: '/RightTurnPaul.glb', index:0},

//   // New actions:
//   jump: { path: '/JumpingPaul.glb', index: 0 },
//   getUp: { path: '/GettingUpPaul.glb', index: 0 },
//   sit: { path: '/SittingPaul.glb', index: 0 },
//   cry: { path: '/CryingPaul.glb', index: 0 },
//   laugh: { path: '/LaughingPaul.glb', index: 0 },
// };
// export default animationList;

//code 2
// const animationList = {
//   walk: { path: '/WalkingPaul.glb', index: 0 },
//   run: { path: '/RunningPaul.glb', index: 0 },
//   idle: { path: '/IdlePaul.glb', index: 0 },
//   leftTurn: { path: '/LeftTurnPaul.glb', index: 0 },
//   rightTurn: { path: '/RightTurnPaul.glb', index: 0 },

//   a: { path: '/BackFlipToUppercutPaul.glb', index: 0 },
//   b: { path: '/BeingElectrocutedPaul.glb', index: 0 },
//   c1: { path: '/BicycleCrunchPaul.glb', index: 0 },
//   d: { path: '/CryingPaul.glb', index: 0 },
//   e: { path: '/DribblePaul.glb', index: 0 },
//   f: { path: '/DyingPaul.glb', index: 0 },
//   g: { path: '/FallenIdlePaul.glb', index: 0 },
//   h: { path: '/FallingPaul.glb', index: 0 },
//   i: { path: '/GettingUpPaul.glb', index: 0 },
//   j: { path: '/GolfDrivePaul.glb', index: 0 },
//   k: { path: '/GuitarPlayingPaul.glb', index: 0 },
//   l: { path: '/HeadSpinningPaul.glb', index: 0 },
//   m: { path: '/IdlePaul.glb', index: 0 }, // reuse for idle
//   n: { path: '/IllegalHeadbuttPaul.glb', index: 0 },
//   o: { path: '/JumpingPaul.glb', index: 0 },
//   p: { path: '/KissPaul.glb', index: 0 },
//   q: { path: '/KnockedOutPaul.glb', index: 0 },
//   r1: { path: '/LaughingPaul.glb', index: 0 },
//   s: { path: '/LeftTurnPaul.glb', index: 0 },
//   t: { path: '/MmaKickPaul.glb', index: 0 },
//   u: { path: '/OffensiveIdlePaul.glb', index: 0 },
//   v: { path: '/PianoPlayingPaul.glb', index: 0 },
//   w: { path: '/PrayingPaul.glb', index: 0 },
//   x: { path: '/PullingARopePaul.glb', index: 0 },
//   y: { path: '/PunchingPaul.glb', index: 0 },
//   z: { path: '/PuttingDownPaul.glb', index: 0 },
//   one: { path: '/RightTurnPaul.glb', index: 0 },
//   two: { path: '/RopeClimbPaul.glb', index: 0 },
//   three: { path: '/RunningPaulPaul.glb', index: 0 },
//   four: { path: '/SalsaDancingPaul.glb', index: 0 },
//   five: { path: '/SittingPaul.glb', index: 0 },
//   six: { path: '/WalkingPaul.glb', index: 0 },
// };

// export default animationList;

//code 3
const animationList = {
  a: { path: '/BackFlipToUppercutPaul.glb', index: 0 },
  b: { path: '/BeingElectrocutedPaul.glb', index: 0 },
  c1: { path: '/BicycleCrunchPaul.glb', index: 0 },
  cry: { path: '/CryingPaul.glb', index: 0 },
  d: { path: '/CryingPaul.glb', index: 0 },
  e: { path: '/DribblePaul.glb', index: 0 },
  f: { path: '/DyingPaul.glb', index: 0 },
  five: { path: '/SittingPaul.glb', index: 0 },
  g: { path: '/GettingUpPaul.glb', index: 0 },
  getUp: { path: '/GettingUpPaul.glb', index: 0 },
  h: { path: '/FallingPaul.glb', index: 0 },
  i: { path: '/GettingUpPaul.glb', index: 0 },
  idle: { path: '/IdlePaul.glb', index: 0 },
  j: { path: '/GolfDrivePaul.glb', index: 0 },
  jump: { path: '/JumpingPaul.glb', index: 0 },
  k: { path: '/GuitarPlayingPaul.glb', index: 0 },
  l: { path: '/HeadSpinningPaul.glb', index: 0 },
  laugh: { path: '/LaughingPaul.glb', index: 0 },
  leftTurn: { path: '/LeftTurnPaul.glb', index: 0 },
  m: { path: '/IdlePaul.glb', index: 0 },
  n: { path: '/IllegalHeadbuttPaul.glb', index: 0 },
  o: { path: '/JumpingPaul.glb', index: 0 },
  one: { path: '/RightTurnPaul.glb', index: 0 },
  p: { path: '/KissPaul.glb', index: 0 },
  q: { path: '/KnockedOutPaul.glb', index: 0 },
  r1: { path: '/LaughingPaul.glb', index: 0 },
  rightTurn: { path: '/RightTurnPaul.glb', index: 0 },
  run: { path: '/RunningPaul.glb', index: 0 },
  s: { path: '/LeftTurnPaul.glb', index: 0 },
  sit: { path: '/SittingPaul.glb', index: 0 },
  six: { path: '/WalkingPaul.glb', index: 0 },
  t: { path: '/MmaKickPaul.glb', index: 0 },
  three: { path: '/RunningPaulPaul.glb', index: 0 },
  two: { path: '/RopeClimbPaul.glb', index: 0 },
  u: { path: '/OffensiveIdlePaul.glb', index: 0 },
  v: { path: '/PianoPlayingPaul.glb', index: 0 },
  w: { path: '/PrayingPaul.glb', index: 0 },
  walk: { path: '/WalkingPaul.glb', index: 0 },
  x: { path: '/PullingARopePaul.glb', index: 0 },
  y: { path: '/PunchingPaul.glb', index: 0 },
  z: { path: '/PuttingDownPaul.glb', index: 0 },
  aa: { path: '/FallenIdlePaul.glb', index: 0 },
  bb: { path: '/SalsaDancingPaul.glb', index: 0 },
};

export default animationList;
